### ISSUE TITLE
Karbon's "new server" message does not work

### ISSUE THREAD

**Issue by CerebralDatabank** [Karbon-Discord/Karbon#14]
After kicking the Karbon bot from my Discord server and re-adding it (using the latest bot invite URL pinned to the general channel of the Karbon's Lounge Discord server), the "new server" message does not appear in Karbon's Lounge or my server.

**Comment by CerebralDatabank** [comment]
First issue :)

**Comment by jsaji06** [comment]
Fixed the issue. Should be working.

**Comment by CerebralDatabank** [comment]
Just tested (2018-10-20T19:08:58-05:00), does not work.
(elementz beat me to reopening the issue)

**Comment by jsaji06** [comment]
Fixed the issue. Should be working.
